### ISSUE TITLE
About generating pseudo labels

### ISSUE THREAD

**Issue by iscyy** [wangerxiao001/yolov5_SSL#1]
Hello author, after I use your code to execute train_mt.py, after the step of generating best.pt, I still don't understand how to implement semi-supervised? How to automatically generate tags, and how to use the generated tags to continue training?

**Comment by wangerxiao001** [comment]
It was based on the pseudo label scheme, more details please refer to to [unbiased teacher](https://arxiv.org/abs/2102.09480)
